version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  pre_build:
    commands:
      - chmod +x node_modules/.bin/next
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "✅ Build completed"

artifacts:
  base-directory: build
  files:
    - '**/*'
