version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "==> Installing dependencies..."
      - npm ci

  pre_build:
    commands:
      - echo "==> Syncing posts from S3..."
      - aws s3 sync s3://$S3_BUCKET_NAME/posts/ posts/ --region us-east-2
      - echo "==> Files in posts/ after sync:"
      - ls -lh posts/

  build:
    commands:
      - echo "==> Files in posts/ before build:"
      - ls -lh posts/
      - echo "==> Starting Next.js build..."
      - npm run build
      - echo "==> Files in posts/ after build:"
      - ls -lh posts/

  post_build:
    commands:
      - echo "✅ Build completed"
      - echo "Using bucket $S3_BUCKET_NAME"
      - echo "📤 Uploading build/ to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete --exclude "posts/*" --region us-east-2
      - echo "🔄 Invalidating CloudFront cache..."
      - aws cloudfront create-invalidation --distribution-id $E75NWUXVORIHR --paths "/*"

artifacts:
  base-directory: build
  files:
    - '**/*'
