version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm install
  build:
    commands:
      - npm run build
      - npx next export -o build  # Keep this line for static output
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  base-directory: build
  files:
    - "**/*"
