version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  build:
    commands:
      - npm run build
  post_build:
  commands:
    - echo "✅ Build completed"
    - echo "📤 Uploading build/ to S3..."
    - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete --region us-east-2
    - echo "📤 Uploading posts/ to S3..."
    - aws s3 cp posts/ s3://$S3_BUCKET_NAME/posts/ --recursive --region us-east-2 

artifacts:
  base-directory: build
  files:
    - '**/*'
