version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - npm ci
  pre_build:
    commands:
      # Sync all posts from S3 into the local posts/ directory
      - aws s3 sync s3://$S3_BUCKET_NAME/posts/ posts/ --region us-east-2
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "✅ Build completed"
      - echo "Using bucket $S3_BUCKET_NAME"
      - echo "📤 Uploading build/ to S3..."
      - aws s3 sync build/ s3://$S3_BUCKET_NAME/ --delete --region us-east-2
      # Do NOT upload posts/ again!

artifacts:
  base-directory: build
  files:
    - '**/*'
