name: Generate Daily Blog Post

on:
  # Every day at midnight UTC. Adjust as needed!
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Sync Down Existing Posts from S3
        run: |
          mkdir -p posts
          aws s3 cp s3://$AWS_S3_BUCKET/posts/ posts/ --recursive --region us-east-2

      - name: Remove Local trigger.txt (if present)
        run: rm -f posts/trigger.txt || true

      - name: Generate Blog Post
        run: node scripts/generatePosts.js

      - name: Check Posts Directory
        run: ls -lh posts/

      - name: Upload All Posts to S3 (No Delete)
        run: aws s3 cp posts/ s3://$AWS_S3_BUCKET/posts/ --recursive --region us-east-2

      - name: Upload New trigger.txt to S3
        run: |
          echo "trigger" > posts/trigger.txt
          aws s3 cp posts/trigger.txt s3://$AWS_S3_BUCKET/posts/trigger.txt --region us-east-2

      - name: Show S3 Bucket Contents After Upload
        run: aws s3 ls s3://$AWS_S3_BUCKET/posts/ --recursive --region us-east-2