name: Generate Monthly Blog Post

on:
  schedule:
    - cron: '0 0 1 * *' # Runs on the 1st of every month at midnight UTC
  workflow_dispatch:

jobs:
  generate-post:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm ci

      - name: Generate Blog Post
        run: node scripts/generatePosts.js

      - name: Upload to S3
        run: |
           aws s3 cp posts/ s3://$AWS_S3_BUCKET/posts/ --recursive --acl public-read --region  us-east-2
